@startuml
'https://plantuml.com/sequence-diagram

autonumber
title 车船票下单时序图
actor APP
APP -> 业务端: 用户选定座位提交
业务端 -> 业务端: 业务端创建初始业务订单
业务端 -> BOOKMEBUS: 将对应的座位信息提交至第三方进行锁位
APP -> APP: 订单添加出行人信息
APP -> 业务端: 点击去付款提交按钮
业务端 -> 业务端: 增加订单关联的出行人信息
业务端 -> 中台: 调用中台接口创建聚合订单
中台 -> 中台: 中台订单的创建流程执行
中台 -> MQ: 发送聚合订单创建结果MQ
中台 -> 业务端: 接口返回聚合订单创建结果

alt 聚合订单创建成功
 业务端 -> 业务端: 修改订单状态为待支付
 业务端 -> 中台: 调用支付单接口创建支付单
 中台 -> 中台: 创建支付单
 中台 -> 业务端: 返回支付单相关信息
 alt 创建支付单成功
 业务端 -> APP: 返回支付订单相关信息
 APP -> 中台: 拉起收银台进行支付
 中台 -> 中台: 进行支付操作
 中台 -> MQ: 发送支付结果MQ
 中台 -> APP: 接口返回支付结果信息
    alt 订单支付成功
         APP -> APP: 订单完成
    else 订单支付失败
         APP -> APP: 重新拉起支付或进行其他操作
    end
 MQ -> 业务端: 推送支付结果信息至业务端
    alt 订单支付成功
         业务端 -> 业务端: 修改订单状态为待出行
         业务端 -> BOOKMEBUS: 下单完成，通知第三方，订单下单成功
         BOOKMEBUS -> BOOKMEBUS: 下单成功，生成核销码
         BOOKMEBUS -> 业务端: 回传核销码至业务端
    else 订单支付失败
         业务端 -> 业务端: 等待用户后续操作
    end
 else 创建支付单失败
 业务端 -> APP: 初始化支付单失败，请重新操作
 end
else 聚合订单创建失败
 业务端 -> APP: 操作失败，请重新下单
 业务端 -> 业务端: 等待用户后续操作
end

@enduml