@startuml
title 订单状态流转
[*] --> 初始化
初始化 -> 初始化 : 用户选座完成，进入添加出行人信息页面
初始化 --> 待付款 : 用户提交支付
待付款 --> 待出行 : 用户支付成功
初始化 --> 已取消 : 用户未在八分钟内完成订单下单
待出行 --> 已取消 : 用户申请取消
待出行 --> 已取消 : 核销码已过期
已取消 --> [*]
待出行 --> 已完成 : 核销码全部核销
已完成 --> [*]
@enduml